import { Order } from "src/types/order.interface";

const orders: Order[] = [
  {
    id: "1",
    status: "pending",
    productImage: require("../assets/pictures/auth/background.png"),
    productName: "Rau củ tươi",
    quantity: 3,
    weight: "20kg",
    price: "250.000đ",
    pickupAddress: "Chợ Bến Thành, Quận 1, TP. Hồ Chí Minh",
    deliveryAddress: "Hồ Hoàn Kiếm, Hoàn Kiếm, Hà Nội",
    pickupContact: "Trần Văn Minh",
    pickupPhone: "0903123456",
    deliveryContact: "Nguyễn Thị Hoa",
    deliveryPhone: "0912345678",
    pickupLatitude: 10.772461,
    pickupLongitude: 106.698055,
    deliveryLatitude: 21.028511,
    deliveryLongitude: 105.854167,
    time: "Đơn hàng của bạn đang chờ xác nhận",
    tag: "Chờ xác nhận",
  },
  {
    id: "2",
    status: "picking",
    productImage: require("../assets/pictures/auth/background.png"),
    productName: "Rau củ tươi",
    quantity: 1,
    weight: "10kg",
    price: "250.000đ",
    pickupAddress: "Vincom Center, 70 Lê Thánh Tôn, Quận 1, TP. Hồ Chí Minh",
    deliveryAddress: "Cầu Rồng, Sơn Trà, Đà Nẵng",
    pickupContact: "Lê Hoàng Phúc",
    pickupPhone: "0938456123",
    deliveryContact: "Phạm Thị Mai",
    deliveryPhone: "0976123456",
    pickupLatitude: 10.776889,
    pickupLongitude: 106.700806,
    deliveryLatitude: 16.061556,
    deliveryLongitude: 108.227056,
    time: "Thời gian lấy hàng ước tính 1 ngày",
    tag: "Đang lấy hàng",
  },
  {
    id: "3",
    status: "picking",
    productImage: require("../assets/pictures/auth/background.png"),
    productName: "Rau củ tươi",
    quantity: 1,
    weight: "25kg",
    price: "200.000đ",
    pickupAddress: "Chợ Đồng Xuân, Hoàn Kiếm, Hà Nội",
    deliveryAddress: "Chợ Hàn, Hải Châu, Đà Nẵng",
    pickupContact: "Nguyễn Văn Hùng",
    pickupPhone: "0968123456",
    deliveryContact: "Trần Thị Lan",
    deliveryPhone: "0923456789",
    pickupLatitude: 21.036600,
    pickupLongitude: 105.852200,
    deliveryLatitude: 16.067800,
    deliveryLongitude: 108.220800,
    time: "Thời gian lấy hàng ước tính 1 ngày",
    tag: "Đang lấy hàng",
  },
  {
    id: "4",
    status: "picking",
    productImage: require("../assets/pictures/auth/background.png"),
    productName: "Rau củ tươi",
    quantity: 10,
    weight: "10kg",
    price: "250.000đ",
    pickupAddress: "Big C Thăng Long, Trần Duy Hưng, Hà Nội",
    deliveryAddress: "Aeon Mall Tân Phú, Tân Phú, TP. Hồ Chí Minh",
    pickupContact: "Phạm Minh Quân",
    pickupPhone: "0987654321",
    deliveryContact: "Lý Thị Hạnh",
    deliveryPhone: "0909123456",
    pickupLatitude: 21.003600,
    pickupLongitude: 105.792000,
    deliveryLatitude: 10.802600,
    deliveryLongitude: 106.628200,
    time: "Thời gian giao hàng ước tính 1 ngày",
    tag: "Đang giao hàng",
  },
  {
    id: "5",
    status: "review",
    productImage: require("../assets/pictures/auth/background.png"),
    productName: "Rau củ tươi",
    quantity: 1,
    weight: "20kg",
    price: "200.000đ",
    pickupAddress: "Chợ Hàn, Hải Châu, Đà Nẵng",
    deliveryAddress: "Vincom Bà Triệu, Hai Bà Trưng, Hà Nội",
    pickupContact: "Võ Thành Long",
    pickupPhone: "0911222333",
    deliveryContact: "Nguyễn Thị Thu",
    deliveryPhone: "0944333222",
    pickupLatitude: 16.073700,
    pickupLongitude: 108.219900,
    deliveryLatitude: 21.013000,
    deliveryLongitude: 105.846000,
    time: "",
    tag: "",
  },
  {
    id: "6",
    status: "cancelled",
    productImage: require("../assets/pictures/auth/background.png"),
    productName: "Rau củ tươi",
    quantity: 1,
    weight: "20kg",
    price: "200.000đ",
    pickupAddress: "Landmark 81, Bình Thạnh, TP. Hồ Chí Minh",
    deliveryAddress: "Cầu Tràng Tiền, Phú Hội, TP. Huế",
    pickupContact: "Nguyễn Quang Hải",
    pickupPhone: "0988111222",
    deliveryContact: "Trần Thị Ngọc",
    deliveryPhone: "0933222111",
    pickupLatitude: 10.794167,
    pickupLongitude: 106.721944,
    deliveryLatitude: 16.463600,
    deliveryLongitude: 107.590800,
    time: "Hoàn tiền thành công",
    tag: "Đã huỷ",
  },
];

export default orders;